title: Dictionaries in Python
hero_image: images/banner.png
subtitle: python-basic-dictionaries subtitle
description: python-basic-dictionaries description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Dictionaries in Python
