title: Dictionaries in Python
hero_image: images/banner.png
description: python-basic-dictionaries description
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technologies: "python"
steps:
  - title: Dictionaries in Python
