---
title: Diccionarios en Python
hero_image: images/banner.png
description: Diccionarios de Python y cómo usarlos
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - 
    title: Diccionarios en Python
